Teste deploy sem os testes

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -24,11 +24,23 @@ jobs:
       - name: Compilação
         run: mvn -B package --file pom.xml -DskipTests
 
-      - name: Testes
-        run: mvn test
+      #- name: Testes
+        #run: mvn test
 
-      - name: Resultados
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure()
-        with:
-          report_paths: 'target/surefire-reports/TEST-*.xml'
+      #- name: Resultados
+        #uses: mikepenz/action-junit-report@v4
+        #if: success() || failure()
+        #with:
+          #report_paths: 'target/surefire-reports/TEST-*.xml'
+
+  deploy:
+    needs: ["compilacao-e-teste"]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Deploy
+        if: github.ref == 'refs/heads/main'
+        env:
+          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
+        run: |
+          curl "$render_deploy_hook_url"
